### ISSUE TITLE
Adding a host should have commctl, and documentation

### ISSUE THREAD

**Issue by jberkus** [projectatomic/commissaire#193]
There's two issues with adding a host under Commissaire right now:

1. The only documentation is a single example curl command, whose elements aren't explained.  For example, what private key are you providing?  Why?  What needs to be installed on the host before you can add it?

2. There should be a commctl command for adding a host.

**Comment by ashcrow** [comment]
> The only documentation is a single example curl command, whose elements aren't explained. For example, what private key are you providing? Why?

I'll update the documentation with this information.

> What needs to be installed on the host before you can add it?

The Linux kernel, ssh, and python (due to ansible's needs). In almost all cases this ends up being 'nothing extra'.

> There should be a commctl command for adding a host.

We do have a ``commctl`` command for host additions but it looks like we missed adding it to the documentation. That's a quick and easy fix which I'll handle as well.

**Comment by ashcrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rM3jbT9z&#x2F;408-multi-host-mgr-update-commctl-documentation"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [multi-host-mgr] Update commctl documentation</a>

**Comment by ashcrow** [comment]
@jberkus PTAL https://github.com/projectatomic/commissaire/pull/198
