### ISSUE TITLE
Provide a Configurable Logging Mechanism

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/commissaire#26]
In the MVP version of commissaire we had configurable logging. `commissaire` should provide a common configurable logging mechanism for other `commissaire` components to use.

MVP Examples:
- https://github.com/projectatomic/commissaire-mvp/blob/master/src/commissaire/script.py#L318-L330
- https://github.com/projectatomic/commissaire-mvp/blob/master/conf/logger.json

**Comment by intlabs** [comment]
I've put together a PoC in containers with [oslo.log](http://docs.openstack.org/developer/oslo.log/) and [oslo.config](http://docs.openstack.org/developer/oslo.config/).

It takes 2 mins to set up:
- [setup-commissaire-oslo-p.sh](https://gist.github.com/intlabs/c49c2f5858b617b3a87e6d817bd9c933#file-setup-commissaire-oslo-poc-sh)
- or to just check out the options:
  
  `docker run -it --rm  docker.io/port/commissaire-server:d1e43f1 --help`

This is obviously a massive change, it pulls in quite a few dependencies - and it would change the primary config file format away from json: http://docs.openstack.org/developer/oslo.config/cfg.html#loading-config-files
Olso.config is, however, capable of meeting the demands of https://github.com/projectatomic/commissaire-service/issues/21, I think.

If this is a viable approach it would not take long for me to put together a PR with this implemented properly.

My motivation for doing this is because I'm working on a Keystone authentication module that will enable Commissaire to operate as an OpenStack Service. From there it would be trivial to write a plugin/driver for Heat, and then let end users manage Commissaire deployed clusters via Magnum. So from a personal perspective I'd quite like to work with the same frameworks, but please feel free to reject this - I won't take offense :)

The changes made to commissaire-service-investigator (as an example) for this quick hack are here:
https://github.com/portdirect/commissaire-service/commit/03c4c1f01ac8f74934e32306461430ee5f0156d4#diff-ced228e29ff2012da9cf65447d7080d9R10

**Comment by ashcrow** [comment]
Thanks @intlabs! I'll take a look at it this morning.

**Comment by ashcrow** [comment]
@intlabs Overall the output looks good. I've written the pros and cons I can see below in the notes. My biggest concern is the INI instead of json for configuration files. It's true that it's common, but more complex configuration files, such as logging configs, in INI format are harder to follow IMHO. If we end up going this direction do you think it would make sense to start with https://github.com/projectatomic/commissaire/issues/26 and reuse it in other components (such as `commissaire-service`)?

@mbarnes I'm interested on your take as well.

# Notes

## Pros
- Good license (ASLv2.0)
- CLI options looks really, really nice
- Gets us out of the business of CLI and config item parsing

## Cons
- Adds 37MB of lib dependencies
  - 33MB if just `oslo.config`
  - Full 37MB with `oslo.log`
- INI files instead of json

**Comment by mbarnes** [comment]
I'm a little confused.  Are we talking about just converting the logging configuration to INI, or the entire `commissaire.conf` configuration?

I think the logging configuration has a simple enough structure to work fairly well with INI format (unique group names + uniform options).  But INI is terrible for complex structures like an array of dictionaries, which we'll need for plugin configurations, etc.

I guess I'm +0 if it's just the logging config + extra dependencies, but -1 if we're talking `commissaire.conf` as well.

**Comment by intlabs** [comment]
@ashcrow: the biggest advantage of using Oslo libs is that they are pretty extensible - so if we were to take this approach the best place to implement it would be here, providing entry points that other components can use, as it provides a very nice framework for solving issues like . I find INI files easier to visually parse than json, but I also have terrible taste in music, so make of that what you will.

The cons you mention are irrefutable, but I'll try anyway :) the [deps](https://github.com/openstack/oslo.config/blob/master/requirements.txt) are large but add a number of nice-to-haves including [debtcollector](http://docs.openstack.org/developer/debtcollector/examples.html), which makes shared configs between components much easier to manage later on. INI certainly is limited, a few OpenStack projects end up doing what I did here for the basic auth and storage backends:
- use oslo.config to define location of your json/yaml configs.
- parse that however you need.

The storage config could be represented in INI with something like:

```
[storage]
enabled_backends = etcd_london,kube_tokyo

[storage.etcd_london]
type = etcd
url = blah
ca = ...
[storage.kube_tokyo]
type = kube
key = value
```

Which is the approach taken in some other OpenStack projects (eg Cinder) for similar problems.

**Comment by intlabs** [comment]
@mbarnes: Sorry I wrote the last post without seeing your reply. I would be perfectly happy to implement this using oslo.config only for logging, cli options and locations of the json config files; leaving the existing config files and parsing well alone.

**Comment by ashcrow** [comment]
>  but I also have terrible taste in music

HA! :laughing: 

> oslo.config only for logging, cli options and locations of the json config files

I think this is a good compromise and it leaves the door open to switch to `oslo.config` in the future if we have consensus. @intlabs put together a PR and we'll review it asap :smile:.

**Comment by gbraad** [comment]
What is the status of this task? /cc: @intlabs @ashcrow

**Comment by ashcrow** [comment]
I defer to @intlabs. I believe this was his first week after recovering from the OpenStack Summit.

**Comment by ashcrow** [comment]
```
07:41:23   portdirect | working on logging again atm - will have this done either this afternoon of first thing tomorrow
07:41:29      ashcrow | portdirect: gbraad was curious about status https://github.com/projectatomic/commissaire/issues/26#issuecomment-259072241
07:41:57   portdirect | could do with a bit of input re config files, I've been using this: https://gist.github.com/intlabs/245847636214fca9381a83fa00881044
07:42:02      ashcrow | portdirect: perfect! If you run into any issues let us know and we'll lend a hand too!
07:42:22      ashcrow | mbarnes: mind taking a gander at that his morning?
07:42:23      mbarnes | all in one, nice!
07:42:27      mbarnes | will do
07:42:48   portdirect | that answers my question: is it better in one or two files?
```
